import React, { useMemo, useState } from 'react';
import './product-features.css';

export function ResearchHub({ saved, toggleSave, open }) {
  const [query, setQuery] = useState('');
  const [topic, setTopic] = useState('All topics');
  const topics = ['All topics', 'Models', 'Research', 'Policy'];
  const results = useMemo(() => window.unboxingStories.filter(story => {
    const haystack = `${story.title} ${story.deck} ${story.tag}`.toLowerCase();
    return (topic === 'All topics' || story.tag.toLowerCase() === topic.toLowerCase()) && haystack.includes(query.toLowerCase());
  }), [query, topic]);
  return <><header><div><p className="eyebrow">GO DEEPER</p><h1>Find the signal,<br/><i>skip the noise.</i></h1></div></header><section className="research-hero"><p>Search the stories and concepts you want to understand. Every result is grouped with its most useful sources.</p><div className="search-live"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search agents, models, regulation…"/>{query && <button onClick={()=>setQuery('')}>Clear</button>}</div><div className="filter-row">{topics.map(x=><button key={x} onClick={()=>setTopic(x)} className={topic===x?'selected':''}>{x}</button>)}</div></section><section className="result-head"><p className="eyebrow">{results.length} STORY {results.length===1?'':'IES'} FOUND</p><span>Searches across topics, sources, and summaries</span></section><section className="result-grid">{results.map(story=><article className="result-card" key={story.title}><div><span className="tag">{story.tag}</span><span className="read">{story.mins}</span></div><h2>{story.title}</h2><p>{story.deck}</p><footer><button onClick={()=>open(story)}>Read story →</button><button onClick={()=>toggleSave(story.title)} className={saved.includes(story.title)?'is-saved':''}>{saved.includes(story.title)?'★ Saved':'☆ Save'}</button></footer></article>)}{!results.length&&<div className="no-results"><span>⌕</span><h2>No stories yet</h2><p>Try a broader search or another topic.</p></div>}</section></>;
}

export function LearningDashboard({ saved, toggleSave, open }) {
  const [playlist, setPlaylist] = useState([]);
  const [notify, setNotify] = useState(true);
  const items = window.unboxingStories.filter(x=>saved.includes(x.title));
  const addToPlaylist = title => setPlaylist(p=>p.includes(title)?p.filter(x=>x!==title):[...p,title]);
  return <><header><div><p className="eyebrow">YOUR SPACE</p><h1>Keep your curiosity<br/><i>in motion.</i></h1></div><span className="streak">✦ 3-day learning streak</span></header><section className="learning-stats"><div><strong>{saved.length}</strong><span>saved stories</span></div><div><strong>{playlist.length}</strong><span>in your playlist</span></div><div><strong>{notify?'Sun':'Off'}</strong><span>weekly recap</span></div></section><section className="playlist-section"><div className="section-heading"><div><p className="eyebrow">LEARNING PLAYLIST</p><h2>Your next deep dive</h2></div><span>{playlist.length} items</span></div>{items.length ? <div className="playlist-list">{items.map((story,i)=><article key={story.title}><span className="playlist-number">0{i+1}</span><div><small>{story.tag} · {story.mins}</small><h3>{story.title}</h3><p>{story.deck}</p><button onClick={()=>open(story)}>Continue reading →</button></div><aside><button onClick={()=>addToPlaylist(story.title)} className={playlist.includes(story.title)?'in-playlist':''}>{playlist.includes(story.title)?'✓ In playlist':'+ Add to playlist'}</button><button onClick={()=>toggleSave(story.title)}>Remove</button></aside></article>)}</div>:<div className="empty-state"><span>☆</span><h2>Your learning queue is ready when you are.</h2><p>Save a story from the timeline or research page to revisit it here.</p></div>}</section><section className="reminder-card"><div><span>✦</span><p className="eyebrow">WEEKLY LEARNING NUDGE</p><h2>Get a thoughtful recap every Sunday.</h2><p>We’ll remind you of saved stories and share a quick summary of what you have not opened yet.</p></div><button onClick={()=>setNotify(!notify)} className={notify?'toggle-button on':'toggle-button'}><i></i>{notify?'Enabled':'Disabled'}</button></section></>;
}

export function Settings({ user, level, changeLevel, signOut }) {
  return <><header><div><p className="eyebrow">ACCOUNT</p><h1>Your learning,<br/><i>your way.</i></h1></div></header><section className="settings-panel"><div className="account-row"><span>{user.name?.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><div><h2>{user.name}</h2><p>{user.email}</p></div><small>Signed in with Google</small></div><div className="settings-row"><div><h3>Learning level</h3><p>Stories are currently explained for a <b>{level}</b> learner.</p></div><button onClick={changeLevel}>Change level →</button></div><div className="settings-row"><div><h3>Email nudges</h3><p>A weekly recap helps you return to saved stories.</p></div><button disabled>Managed in My learning</button></div><div className="settings-row danger"><div><h3>Sign out</h3><p>You can sign in again at any time.</p></div><button onClick={signOut}>Sign out</button></div></section></>;
}
